# Generated by Django 3.2.13 on 2023-03-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
