# Generated by Django 3.2.13 on 2023-03-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230316_1157'),
        ('accounts', '0003_auto_20230310_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_product',
            field=models.ManyToManyField(related_name='like_users', to='products.Products'),
        ),
    ]
