# Generated by Django 3.2.13 on 2023-03-10 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('point', models.IntegerField()),
                ('serial', models.CharField(max_length=80)),
                ('delivery', models.IntegerField()),
                ('image_main1', models.ImageField(default='default_img.jpg', null=True, upload_to='images/')),
                ('image_main2', models.ImageField(default='default_img.jpg', null=True, upload_to='images/')),
                ('image_main3', models.ImageField(default='default_img.jpg', null=True, upload_to='images/')),
                ('image_main4', models.ImageField(default='default_img.jpg', null=True, upload_to='images/')),
                ('image_main5', models.ImageField(default='default_img.jpg', null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_sub', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='products.products')),
            ],
        ),
    ]
