# Generated by Django 3.2.13 on 2023-03-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsinfo',
            name='image_main',
        ),
        migrations.AddField(
            model_name='products',
            name='image_main',
            field=models.ImageField(default='media/product/default_img.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='productsinfo',
            name='image_sub',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
