# Generated by Django 3.2.13 on 2023-03-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_image_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_main',
            field=models.ImageField(default='images/default_img.jpg', null=True, upload_to='images/'),
        ),
    ]
